"""initial_schema

Revision ID: 49d8ebb9b191
Revises: 
Create Date: 2026-09-14 08:01:57.525393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49d8ebb9b191'
down_revision: Union[str, None] = None
branch_labels: Union[str, Union[Sequence[str], None]] = None
depends_on: Union[str, Union[Sequence[str], None]] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###